
% MATLAB Code from Sensor Array Analyzer App

% Generated by MATLAB 24.2 and Phased Array System Toolbox 24.2

% Generated on 31-Mar-2025 15:52:36

% Create a uniform rectangular array
Array = phased.URA('Size',[16 16],...
    'Lattice','Rectangular','ArrayNormal','x');
% The multiplication factor for lambda units to meter conversion
Array.ElementSpacing = [0.5 0.5]*0.03;
% Calculate Row taper
rwind = ones(1,16).';
% Calculate Column taper
cwind = ones(1,16).';
% Calculate taper
taper = rwind*cwind.';
Array.Taper = taper.';

% Create an isotropic antenna element
Elem = phased.IsotropicAntennaElement;
Elem.BackBaffled = true;
Elem.FrequencyRange = [0 10000000000];
Array.Element = Elem;

% Assign Frequencies and Propagation Speed
Frequency = 10000000000;
PropagationSpeed = 300000000;

% Assign Steering Angles
SteeringAngles = [30;0];
% Assign Phase shift quantization bits
PhaseShiftBits = 0;

% Create Figure

% Plot Array Geometry
figure;
viewArray(Array,'ShowNormals',false,...
    'ShowTaper',false,'ShowIndex','None',...
    'ShowLocalCoordinates',true,'ShowAnnotation',false,...
    'Orientation',[0;0;0]);

% Find the weights
w = zeros(getNumElements(Array), length(Frequency));
for idx = 1:length(Frequency)
    SteerVector = phased.SteeringVector('SensorArray', Array,...
        'PropagationSpeed', PropagationSpeed, ...
        'NumPhaseShifterBits', PhaseShiftBits(idx));
    w(:, idx) = step(SteerVector, Frequency(idx), SteeringAngles(:, idx));
end

% Plot 2d azimuth graph
format = 'rectangular';
cutAngle = 0;
plotType = 'Directivity';
plotStyle = 'Overlay';
figure;
pattern(Array, Frequency, -180:180, cutAngle, 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format ,'weights', w, ...
    'Type', plotType, 'PlotStyle', plotStyle);
hold on
pattern(Array, Frequency*(0.95), -180:180, cutAngle, 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format ,'weights', w, ...
    'Type', plotType, 'PlotStyle', plotStyle);
hold off